#!/bin/sh

set -x -eo pipefail

###
# Installations
###

apk add --no-cache curl git=${GIT_VERSION} python3=${PYTHON3_VERSION} bash=${BASH_VERSION} ca-certificates=${CACERTIFICATES_VERSION} perl=${PERL_VERSION}

pip3 install --no-cache --upgrade pip setuptools wheel
pip3 install pre-commit==${PRE_COMMIT_VERSION}
chmod +x /usr/bin/pre-commit

curl -sSLo /usr/local/bin/terraform-docs \
  https://github.com/segmentio/terraform-docs/releases/download/${TERRAFORM_DOCS_VERSION}/terraform-docs-${TERRAFORM_DOCS_VERSION}-linux-amd64
ln -s /usr/local/bin/terraform-docs /usr/local/bin/terraform-docs${TERRAFORM_DOCS_VERSION}
chmod +x /usr/local/bin/terraform-docs

curl -sSLo /resources/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
  https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
unzip /resources/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin

curl -sSLo /resources/helm-v${HELM_VERSION}-linux-amd64.tar.gz \
  https://kubernetes-helm.storage.googleapis.com/helm-v${HELM_VERSION}-linux-amd64.tar.gz
tar -xzf /resources/helm-v${HELM_VERSION}-linux-amd64.tar.gz
install -m 755 linux-amd64/helm /usr/local/bin/

curl -sSLo /tmp/tflint${TFLINT_VERSION}.zip \
https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip
unzip /tmp/tflint${TFLINT_VERSION}.zip -d /tmp
install -m 755 /tmp/tflint /usr/local/bin/

###
# Cleaning image
###

apk del --no-cache curl

###
# CIS Hardening
###

chmod 0600 /etc/shadow

touch /etc/login.defs
chmod 0444 /etc/login.defs
